# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Drugstore' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Drugstore

  pod 'BarcodeScanner', '~> 4.1'
  pod 'Alamofire', '~> 4.8'
  pod 'AlamofireObjectMapper', '~> 5.2'
  pod 'StatusAlert', '~> 1.1.0'
  pod 'IHProgressHUD', '~> 0.1.4'
end
